# Generated by Django 5.2.5 on 2025-10-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_cetificate_chai_review_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cetificate',
            old_name='chai',
            new_name='chai_n',
        ),
    ]
